### ISSUE TITLE
Button::name()

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#18]
I have the impression that the M5 API generally uses the form getXXX() and setXXX() rather than XXX().
I would expect the accessor for Button's name property to get getName().

If you have found that they're quite inconsistent about this practice, please ignore. But if it's common, it's best to stick to it. I hate switching back and forth between different idioms within the same library.

The Core2 release coding was very inconsistent, but it's best to reduce that.

**Comment by vkichline** [comment]
Same applies to Gesture.

**Comment by ropg** [comment]
Yeah, the getters and setters is all fine and well, but with the amount of variables just adds hundreds and hundreds of lines to the header and source files for (IMHO) no good reason other than that consistency. I think public class variables that would otherwise need two functions and a variable are better off. char* strings are the exception because they are too easy to screw up. Might give the strings another think. Or maybe make them 'String' objects instead, we're not on an Arduino with 128 bytes of RAM here.

**Comment by vkichline** [comment]
I agree, I didn't mean you needed a lot of getters and setters, I just mean when you do have getters, make them consistent with existing code.
`In_eSPI.h`, which is in a related area, almost consistently uses `getThis()`, `getThat()`.
So when I try to get a button's name, I try `button.getName()` and miss.
In the Touch code, generally when I refer to a member by bare name, it's not a function, so next I try `button.name`.
I have to mentally shift gears back and forth, which is tiring. It makes sense to me to have accessors for text, so it's not hard to remember to use `get` for text.
However, maybe this is personal preference that others don't care that much about.

**Comment by ropg** [comment]
`getName()` it is. Have changed your examples accordingly.
