### ISSUE TITLE
PlatformIO Compiler warnings

### ISSUE THREAD

**Issue by vkichline** [ropg/M5Core2#5]
I get the following warning in PlatformIO:

This one is obscure and I get it often enough comparing `char foo[n] == ""`. Suggest replacing `b._label != ""` with `strlen(b._label)`
```
lib\M5Core2\src\utility\M5Button.cpp: In static member function 'static void M5Buttons::drawFunction(Button*, ButtonColors)':
lib\M5Core2\src\utility\M5Button.cpp:328:58: warning: comparison with string literal results in unspecified behaviour [-Waddress]
   if (bc.text != NONE && bc.text != bc.bg && b._label != "") {
                                                          ^
```

An unused variable:
```
lib\M5Core2\src\utility\M5Button.cpp: In member function 'bool Button::read(bool)':
lib\M5Core2\src\utility\M5Button.cpp:97:12: warning: unused variable 'duration' [-Wunused-variable]
   uint32_t duration = _time - _pressTime;
            ^
```

And finally, this one has been there forever; maybe you could fix it with the others:
```
C:\users\van\.platformio\lib\M5Stack\src\utility\In_eSPI.cpp:4345:17: warning: 'char_count' defined but not used [-Wunused-variable]
Compiling .pio\build\m5stack-fire\libafa\M5Core2\M5Touch.cpp.o
 static uint32_t char_count = 0;
                 ^
```

**Comment by ropg** [comment]
Fixed the first two (and another `!= ""` I found), am uncertain about the last because it is not my, and not even M5Stack's code. I think that (also?) needs to be an issue with the makers of that library. If I change it and that library updates, it will be lost.

If we fix it it should be in its own PR so M5Stack can judge what to do and is aware that it was touched.
