### ISSUE TITLE
M5Sounds: Suggestion/Idea/Enhancement

### ISSUE THREAD

**Issue by revta** [ropg/M5Core2#74]
@ropg First, thank you so much for all your work. The Core2 didnt really start to click until I read through your Button and Touch documentation. I like it a lot. The thing I appreciate the most is that it sets up M5Stack code to be compatible with the M5Core2. 

That's the idea for the suggestion. There are so many great M5Stack examples but very few run on the Core2 out of the box. (Specifically community created examples in addition to the included examples...) You can swap the includes and get close, but the one that I've been trying to work through is the sound/speaker setup. 

The idea would be to use the Core2 M5Sounds libarary/branch but also incorporate the M5Stack sound definitions so the Core2 would be backwards compatible with M5Stack (Original Core? I might have my terminology messed up) 

For instance, is there a way to use your M5Sounds library also work with something like 
`M5.Speaker.tone(630)` ?

Is there a reason that you know of that there hasnt been a big push to make as much of the Core2 backwards compatible? 

Thank you for any wisdom! I'm new to this whole git thing.

**Comment by revta** [comment]
After looking at your DTMF example, it appears I can accomplish at least the example I gave with the ".freq" def. followed by start.

**Comment by ropg** [comment]
I'm presently working on Core2ez to the point where it can do the sort of things that M5ez already could. 

Core2ez is Button and Touch in their own library but then turned into a complete widget programming environment.

Finishing it means adding status bar, menus, wifi and all the other functionality in the new framework. That's going to be taking up my time for the coming couple of weeks.

Then that all is going to have to be documented, which is another couple of weeks.

Things will change, sometimes dramatically between here and some point in January when it's all finished.

Sound does need simpler ways of invoking a simple beep or ping, I agree. No way if it'll be backwards compatible given how little software there was for the original M5Stack that uses sound.

I'd rather spend time having ezSound work on the old M5Stack using the built-in DAC instead of the I2C IC, which shouldn't be too hard.


Zooming out: I would not be surprised if M5Stack sells way more Core2 units in the coming year than there ever were M5Stack "classic" 3-button units. As much as liked the thing when it came out: writing things for a touch screen is so much more fun that I can see myself focussing forward. I did consider using the inertial chip to create a cursor on the M5Stack, and that may still be viable, because it would work on various units that have inertial but no touch (like StickC). But that's just a thought for now. I am just one guy writing the vast majority of the code, and I would rather do a great job on a limited amount of hardware than a mediocre job on lots more hardware.

**Comment by revta** [comment]
This is so encouraging and super helpful! Thank you for providing your insight! I am also relieved to hear that you are still working on the Core2. I jumped into the community approximately 3 days after your last commit so I was worried you had moved on to other things. I really appreciate your contributions, it is a ton of work that often goes without thanks. So on behalf of anyone who uses your code, thank you so so much for your contributions! Looking forward to your next releases! If I can help test please dont hesitate to reach out. I'd love the opportunity to help contribute and keep learning!
